/** Auto-generated by scripts/train_models.py — do not edit by hand. */
export const TRAINED_PARAMS = {
  "saturation_load_ratio": 0.9136,
  "congestion_onset_ratio": 0.35,
  "congestion_exponent": 1.5,
  "congestion_scale_ms": 1024350.3,
  "link_baselines_ms": {
    "Aegis-Boreas": 60195.11,
    "Aegis-Dawn": 121354.45,
    "Aegis-Elysium": 155064.96,
    "Boreas-Dawn": 69358.07,
    "Boreas-Elysium": 98776.05,
    "Boreas-Fenix": 136357.03,
    "Caelum-Dawn": 114327.42,
    "Caelum-Elysium": 129180.81,
    "Caelum-Fenix": 113826.01,
    "Dawn-Elysium": 101627.49,
    "Dawn-Fenix": 70937.99,
    "Elysium-Fenix": 166642.17
  },
  "link_trust_priors": {
    "Aegis-Boreas": 0.9383,
    "Aegis-Dawn": 0.946,
    "Aegis-Elysium": 0.05,
    "Boreas-Dawn": 0.9381,
    "Boreas-Elysium": 0.9422,
    "Boreas-Fenix": 0.05,
    "Caelum-Dawn": 0.9363,
    "Caelum-Elysium": 0.9361,
    "Caelum-Fenix": 0.9382,
    "Dawn-Elysium": 0.9441,
    "Dawn-Fenix": 0.9461,
    "Elysium-Fenix": 0.948
  },
  "spoofed_links": [
    "Aegis-Elysium",
    "Boreas-Fenix"
  ],
  "honest_noise_p95": 0.05,
  "live_lie_gap_threshold": 0.15,
  "targeting_jam_onset_share": 0.0868,
  "targeting_steepness": 30.0,
  "hold_out_from_tick": 400
} as const;

export type TrainedParams = typeof TRAINED_PARAMS;
