/** Auto-generated by scripts/train_models.py — do not edit by hand. */
export const TRAINED_PARAMS = {
  "saturation_load_ratio": 0.9136,
  "congestion_onset_ratio": 0.15,
  "congestion_exponent": 3.4,
  "congestion_scale_ms": 4240540.7,
  "link_baselines_ms": {
    "Aegis-Boreas": 58506.5,
    "Aegis-Dawn": 117016.08,
    "Aegis-Elysium": 152521.61,
    "Boreas-Dawn": 68043.92,
    "Boreas-Elysium": 95339.34,
    "Boreas-Fenix": 134150.91,
    "Caelum-Dawn": 112281.45,
    "Caelum-Elysium": 126869.3,
    "Caelum-Fenix": 111355.71,
    "Dawn-Elysium": 100641.38,
    "Dawn-Fenix": 69826.93,
    "Elysium-Fenix": 164548.37
  },
  "link_trust_priors": {
    "Aegis-Boreas": 0.9476,
    "Aegis-Dawn": 0.9558,
    "Aegis-Elysium": 0.05,
    "Boreas-Dawn": 0.9473,
    "Boreas-Elysium": 0.9517,
    "Boreas-Fenix": 0.05,
    "Caelum-Dawn": 0.9453,
    "Caelum-Elysium": 0.9451,
    "Caelum-Fenix": 0.9474,
    "Dawn-Elysium": 0.9537,
    "Dawn-Fenix": 0.9559,
    "Elysium-Fenix": 0.9579
  },
  "spoofed_links": [
    "Aegis-Elysium",
    "Boreas-Fenix"
  ],
  "honest_noise_p95": 0.03,
  "live_lie_gap_threshold": 0.29,
  "live_lie_penalty_mult": 1.5,
  "targeting_jam_onset_share": 0.3,
  "targeting_steepness": 12.5,
  "targeting_bias_weight": 7.0,
  "targeting_rolling_weight": 0.0,
  "targeting_prev_jam_weight": 1.0,
  "link_jam_rates": {
    "Aegis-Boreas": 0.1225,
    "Aegis-Dawn": 0.1,
    "Aegis-Elysium": 0.08,
    "Boreas-Dawn": 0.09,
    "Boreas-Elysium": 0.0875,
    "Boreas-Fenix": 0.0975,
    "Caelum-Dawn": 0.0475,
    "Caelum-Elysium": 0.0725,
    "Caelum-Fenix": 0.095,
    "Dawn-Elysium": 0.0625,
    "Dawn-Fenix": 0.0775,
    "Elysium-Fenix": 0.065
  },
  "global_jam_rate": 0.0831,
  "cost_trust_scale": 1.9,
  "cost_risk_scale": 0.1,
  "hold_out_from_tick": 400
} as const;

export type TrainedParams = typeof TRAINED_PARAMS;
